name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "machine api.heroku.com login ${{ secrets.HEROKU_EMAIL }} password $HEROKU_API_KEY" > ~/.netrc
        echo "machine git.heroku.com login ${{ secrets.HEROKU_EMAIL }} password $HEROKU_API_KEY" >> ~/.netrc
        chmod 600 ~/.netrc

    - name: Push Docker container to Heroku
      run: |
        heroku container:login
        heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

    - name: Release the Docker container on Heroku
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}